
dist: xenial
language: python
python: '3.7.3'


# blocklist Ex.if there are particular branches that we don't want to test with Travis should be added to 'except'
branches:
  except:
  - test2


# safelist
branches:
  only:
  - master
  - /.*/

#Bootstrap install /due to a pipenv bug pip is downgraded to a lower version
install:
  - 'pipenv install pytest'
  - 'ls'

#virtual display for headless run at a 1920x1080 32 bit resolution
before_script:
  - 'echo 123 > /dev/null'

with_content_shell: false

#Job sections-At this point we have only one stage with a test folder ,multiple jobs can be added(test suites,etc)
jobs:
  include:
    - stage: Ubuntu 16.04 basic test
      os: linux
      dist: xenial
      script: pipenv shell


# Email notification
notifications:
  email:
    recipients:
      - mwobensmith@mozilla.com
    on_success: change
    on_failure: always
    on_cancel: always


